//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retter
    {
        public Nullable<int> Rid { get; set; }
        public string Overskrift { get; set; }
        public string Indhold { get; set; }
    }
}
